### ISSUE TITLE
iOS App - Empty Spools showing in inventory tab 

### ISSUE THREAD

**Issue by Aveplatter** [Filament-uno/site#10]
Unable to remove empty spools from my inventory. Causing clutter

**Comment by paul999** [comment]
Yes, you are right. Empty spools should be hidden by default. I will fix it in the next release.

**Comment by paul999** [comment]
I have fixed this locally. The next release of the iOS app will hide empty spools by default from the inventory, what matches both the site as the android app.
I do need to fix a few other small things, so it might take a few days before the update shows up on the App Store.

Thanks for your report!

**Comment by paul999** [comment]
Just as update, the app has just been submitted for review by Apple, and should be available as soon Apple approves it.

**Comment by Aveplatter** [comment]
awesome! Super quick
