### ISSUE TITLE
In IOS Darkmode

### ISSUE THREAD

**Issue by scabackel** [Filament-uno/site#12]
Hi,

i'am using Dark Mode in IOS. If i add a Filament Letters are written Black on Black Ground, so nothing is readeble before saving. In Inventory text is written white on black ground. Hope this is only a small bug for you.

Cool App, Love it 🎉

**Comment by paul999** [comment]
Thanks :).

I will look into it, however it might take  a bit of time due to some personal stuff happening at the moment.

**Comment by paul999** [comment]
I have pushed a fix, will try to submit it later this week to apple. 
Thanks for your report :)
