### ISSUE TITLE
Samsung Galaxy22 not writing NFC tags

### ISSUE THREAD

**Issue by teeja8987** [Filament-uno/site#13]
App on phone does not write to the NFC tags. The message "Hold Tag Near Your Phone" never goes away.  Is this feature not working yet?

**Comment by paul999** [comment]
Hi,

Unfortunately, there is a small bug in the current version of the android app that fails to write NFC tags. I have it already fixed locally, and are hoping to get the release done somewhere during the Christmas break.

**Comment by paul999** [comment]
This update has just been released. If you still have issues please let me know .

**Comment by teeja8987** [comment]
It works perfectly... thanks for the quick response.

Sent with [Proton Mail](https://proton.me/) secure email.
