### ISSUE TITLE
Include roll index in JSON export

### ISSUE THREAD

**Issue by agmlego** [Filament-uno/site#14]
Currently, all of the data for each roll is present in the JSON data export *except* the index, which is what is needed to generate the URL and QR code.

(Use case: I am doing batch printing of labels using mail merge, and have to manually record each roll's index first...)

**Comment by paul999** [comment]
It is actually not a index, but a unique ID, so if you are using it as index, it will cause issues.
But you are absolutely right, there ID (and maybe even URL), should be included. I will have a look this weekend to get it added.

**Comment by paul999** [comment]
This should be now live on the site. I have added the ID, the direct link to the item, and a link to download a image of the QR code.
